import z from 'zod';

const githubRepositoryLicense = z.object({
  key: z.string(),
  name: z.string(),
  url: z.string(),
  spdx_id: z.string(),
  node_id: z.string(),
  html_url: z.string().url().optional(),
});

export type GithubRepositoryLicense = z.infer<typeof githubRepositoryLicense>;

const githubRepositoryOwner = z.object({
  login: z.string(),
  id: z.number(),
  node_id: z.string(),
  avatar_url: z.string().url(),
  gravatar_id: z.string(),
  url: z.string(),
  received_events_url: z.string().url(),
  type: z.string(),
  html_url: z.string().url(),
  followers_url: z.string().url(),
  following_url: z.string().url(),
  gists_url: z.string().url(),
  starred_url: z.string().url(),
  subscriptions_url: z.string().url(),
  organizations_url: z.string().url(),
  repos_url: z.string().url(),
  events_url: z.string().url(),
  site_admin: z.boolean(),
});

export type GithubRepositoryOwner = z.infer<typeof githubRepositoryOwner>;

export const githubRepositoryItem = z.object({
  id: z.number(),
  node_id: z.string(),
  name: z.string(),
  full_name: z.string(),
  owner: githubRepositoryOwner,
  private: z.boolean(),
  html_url: z.string().url(),
  description: z.string(),
  fork: z.boolean(),
  url: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  pushed_at: z.string().datetime(),
  homepage: z.string(),
  size: z.number(),
  stargazers_count: z.number(),
  watchers_count: z.number(),
  language: z.string(),
  forks_count: z.number(),
  open_issues_count: z.number(),
  master_branch: z.string().optional(),
  default_branch: z.string(),
  score: z.number().optional(),
  archive_url: z.string().url(),
  assignees_url: z.string().url(),
  blobs_url: z.string().url(),
  branches_url: z.string().url(),
  collaborators_url: z.string().url(),
  comments_url: z.string().url(),
  commits_url: z.string().url(),
  compare_url: z.string().url(),
  contents_url: z.string().url(),
  contributors_url: z.string().url(),
  deployments_url: z.string().url(),
  downloads_url: z.string().url(),
  events_url: z.string().url(),
  forks_url: z.string().url(),
  git_commits_url: z.string().url(),
  git_refs_url: z.string().url(),
  git_tags_url: z.string().url(),
  git_url: z.string().url(),
  issue_comment_url: z.string().url(),
  issue_events_url: z.string().url(),
  issues_url: z.string().url(),
  keys_url: z.string().url(),
  labels_url: z.string().url(),
  languages_url: z.string().url(),
  merges_url: z.string().url(),
  milestones_url: z.string().url(),
  notifications_url: z.string().url(),
  pulls_url: z.string().url(),
  releases_url: z.string().url(),
  ssh_url: z.string(),
  stargazers_url: z.string().url(),
  statuses_url: z.string().url(),
  subscribers_url: z.string().url(),
  subscription_url: z.string().url(),
  tags_url: z.string().url(),
  teams_url: z.string().url(),
  trees_url: z.string().url(),
  clone_url: z.string().url(),
  mirror_url: z.string().url().nullable(),
  hooks_url: z.string().url(),
  svn_url: z.string().url(),
  forks: z.number(),
  open_issues: z.number(),
  watchers: z.number(),
  has_issues: z.boolean(),
  has_projects: z.boolean(),
  has_pages: z.boolean(),
  has_wiki: z.boolean(),
  has_downloads: z.boolean(),
  archived: z.boolean(),
  disabled: z.boolean(),
  visibility: z.string(),
  license: githubRepositoryLicense,
});
